# Project information
site_name: Landesstatistiken
site_description: 'Landesstatistiken'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://doc.ls.stueber.de'

# Copyright
copyright:
  '&copy; 2024 STÜBER SYSTEMS GmbH : <a href="https://legal.stueber.de/imprint.php">Impressum</a> : <a href="https://legal.stueber.de/privacy.php">Datenschutz</a>'

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/stuebersystems/doc.ls.de'

# Theming
theme: 
    name: material
    language: de
    features:
        - navigation.footer
        - navigation.instant
        - navigation.tabs
        - navigation.top
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
    palette:
        primary: 'blue'
        accent: 'deep orange'
    font: false
    favicon: assets/logos/favicon.ico
    logo: 'assets/logos/logo.svg'
    include_search_page: false
    search_index_only: true
    static_templates:
      - 404.html

# Customization
extra_css:
    - assets/css/custom.css

# Plugins    
plugins:
    - search
    - img2fig

# Extensions    
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.abbr
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.tasklist:
      custom_checkbox: true  
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  
# Navigation  
nav:
- Überblick:
  - Statistikkonzept: index.md
  - Data Warehouse: das-datawarehouse.md
  - Schlüsselverzeichnisse: schluesselverzeichnisse.md
  - Datenprüfung: datenpruefung.md
  - DaVinci Daten exportieren: dav.statistikdaten-exportieren.md
  - Statistikdateien erzeugen: statistikdaten.erstellen.md
  - Legende: legende-statistikfelder.md
  - Bayern:
    - WinLD/AS: bayern/winld.md
  - Berlin:
    - Einstieg: berlin/01.stat.einstieg.md
    - Schlüsselverzeichnisse: berlin/02.schluesselverzeichnisse.md
    - Abiturdatenstatistik: berlin/03.stat.abidaten.md
    - Schülerdatenstatistik: berlin/04.stat.schuelerdaten.md
    - Schülerexport (csv): berlin/05.schuelerdatencsv.md
    - Schülerimport (LUSD): berlin/06.lusd.md    
  - Brandenburg:
    - ABS/BBS: brandenburg/abs-bbs.md
  - Mecklenburg-Vorpommern:
    - Einstieg: mecklenburg-vorpommern/einstieg.md
    - Daten exportieren: mecklenburg-vorpommern/export_sip.md
    - Daten importieren: mecklenburg-vorpommern/import_sip.md
  - Niedersachsen:
    - Einstieg: niedersachsen/einstieg.md
    - KLIMP.TXT: niedersachsen/klimp.md
    - RELIMP.TXT: niedersachsen/relimp.md
  - Nordrhein-Westfalen:
    - Einstieg: nordrhein-westfalen/einstieg.md
    - SIM.TXT: nordrhein-westfalen/schuelerdaten.md
    - LEHRER.TXT: nordrhein-westfalen/lehrerdaten.md
    - ABI.TXT: nordrhein-westfalen/abiturdaten.md
    - EXTERN.DAT: nordrhein-westfalen/stundenplandaten.md
    - GPC Datenerhebung BBS: nordrhein-westfalen/gpc-datenerhebung-bbs.md
    - Aktuelle Version: nordrhein-westfalen/changelog.md
  - Rheinland-Pfalz:
    - ABS/BBS: rheinland-pfalz/abs-bbs.md
    - Schüler-/Klassendaten: rheinland-pfalz/schuler-und-klassendaten.md
    - Lehrerdaten: rheinland-pfalz/lehrerdaten.md
    - Aktuelle Version: rheinland-pfalz/changelog.md
  - Saarland:
    - ABS/BBS: saarland/abs-bbs.md
  - Sachsen:
    - Einstieg: sachsen/einstieg.md
    - Schlüsselpflege: sachsen/schluessel.md
    - Daten exportieren: sachsen/export_saxsvs.md
    - Daten importieren: sachsen/import_saxsvs.md
    - Probleme und Lösungen: sachsen/probleme.md
  - Schleswig-Holstein:
    - Einstieg: schleswig-holstein/einstieg.md
    - Besonderheiten (Archiv): schleswig-holstein/besonderheiten_archiv.md
    - Aktuelle Version: schleswig-holstein/changelog.md
  - Thüringen:
    - ABS/BBS: thueringen/abs-bbs.md
