# Project information
site_name: Landesstatistiken
site_description: 'Landesstatistiken'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://doc.ls.stueber.de'

# Copyright
copyright: © 2020 STÜBER SYSTEMS GmbH

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/stuebersystems/doc.ls.de'

# Theming
theme: 
    name: null
    custom_dir: 'theme'
    language: de
    direction:
    feature:
        tabs: false
    palette:
        primary: 'blue'
        accent: 'deep orange'
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/logos/favicon.ico
    logo: 'assets/logos/logo.svg'
    include_search_page: false
    search_index_only: true
    static_templates:
      - 404.html

# Customization
extra_css:
    - assets/css/custom.css

# Plugins    
plugins:
    - search
    - img2fig
    
# Extensions    
markdown_extensions:
    - admonition    
    - codehilite
  
# Navigation  
nav:
- Überblick:
  - Statistikkonzept: index.md
  - Data Warehouse: das-datawarehouse.md
  - Schlüsselverzeichnisse: schluesselverzeichnisse.md
  - Datenprüfung: datenpruefung.md
  - DAVINCI Daten exportieren: dav.statistikdaten-exportieren.md
  - Statistikdateien erzeugen: statistikdaten.erstellen.md
  - Legende: legende-statistikfelder.md
- Bayern:
  - WinLD/AS: bayern/winld.md
- Berlin:
  - Übersicht: berlin/berlin.md
- Brandenburg:
  - ABS/BBS: brandenburg/abs-bbs.md
- Mecklenburg-Vorpommern:
  - SIP: mecklenburg-vorpommern/sip.md
- Niedersachsen:
  - ABS: niedersachsen/abs.md
  - BBS: niedersachsen/bbs.md
- Nordrhein-Westfalen:
  - Einstieg: nordrhein-westfalen/einstieg.md
  - SIM.TXT: nordrhein-westfalen/schuelerdaten.md
  - LEHRER.TXT: nordrhein-westfalen/lehrerdaten.md
  - ABI.TXT: nordrhein-westfalen/abiturdaten.md
  - EXTERN.DAT: nordrhein-westfalen/stundenplandaten.md
  - GPC Datenerhebung BBS: nordrhein-westfalen/gpc-datenerhebung-bbs.md
  - Aktuelle Version: nordrhein-westfalen/changelog.md
- Rheinland-Pfalz:
  - ABS/BBS: rheinland-pfalz/abs-bbs.md
  - Schüler-/Klassendaten: rheinland-pfalz/schuler-und-klassendaten.md
  - Lehrerdaten: rheinland-pfalz/lehrerdaten.md
  - Aktuelle Version: rheinland-pfalz/changelog.md
- Saarland:
  - ABS/BBS: saarland/abs-bbs.md
- Sachsen:
  - Einstieg: sachsen/einstieg.md
  - Schlüsselpflege: sachsen/schluessel.md
  - Daten exportieren: sachsen/export_saxsvs.md
  - Daten importieren: sachsen/import_saxsvs.md
- Schleswig-Holstein:
  - Einstieg: schleswig-holstein/einstieg.md
  - Besonderheiten (Archiv): schleswig-holstein/besonderheiten_archiv.md
  - Aktuelle Version: schleswig-holstein/changelog.md
- Thüringen:
  - ABS/BBS: thueringen/abs-bbs.md
